### ISSUE TITLE
Error on the theming page? 

### ISSUE THREAD

**Issue by pickleat** [timber/docs#22]
On this page: https://timber.github.io/docs/getting-started/theming/

it shows this code snippet: 
![image](https://user-images.githubusercontent.com/39109475/90846522-f57f1000-e32d-11ea-99cf-283328a9c1df.png)

but when I downloaded the starter theme those files are found at
`wp-content/themes/{timber-starter-theme}/views/single.twig`

Just wanted to check and see if I'm missing anything here, because I spent about 30 minutes rewriting the example file because the `/templates` directory doesn't exist on the theme.

**Comment by gchtr** [comment]
@pickleat That’s definitely an error in the documentation. The file structure was reorganized a bit in the Starter Theme and we forgot to update that in the documentation. We’ll see that we can get this fixed.

**Comment by pickleat** [comment]
Glad I caught it! Let me know if you need help. Appreciate the response!
