### ISSUE TITLE
Wrong filter name in documentation

### ISSUE THREAD

**Issue by bart-jaskulski** [timber/docs#54]
Documentation contains wrong filter name for `retina_resize`. Actual value should be `retina`. The same issue is in v2.0 of documentation.

https://github.com/timber/docs/blob/ba3417a10803bdc2f08ed5b3644a9f9077a6ded7/content/reference/timber-imagehelper.md?plain=1#L362

**Comment by gchtr** [comment]
The name of the filter is `retina`, but the name of the function this filter calls in the back is `retina_resize`, which is a method of `Timber\ImageHelper` see https://github.com/timber/timber/blob/8d9bff23d2677652469badb75dcb607449a18204/lib/ImageHelper.php#L109.

The reference documentation for [`Timber\ImageHelper`](https://timber.github.io/docs/v2/reference/timber-imagehelper/) lists all the available properties and methods in that class in case you want to use `Timber\ImageHelper` directly in your code.

The `retina` filter is documented in the [Images Guide](https://timber.github.io/docs/guides/cookbook-images/).
