### ISSUE TITLE
Mobile menu not opening after navigating between pages.

### ISSUE THREAD

**Issue by Levdbas** [timber/docs#62]
**Bug description**

After the first navigation to another page on a mobile device the mobile menu doesn't work anymore. It requires a full page reload to get the menu to work again. Upon closer inspection I found out that there is no more event binded to `.js-menu-open` after the initial navigation.

Browsers:

- Chrome desktop/safari
- Firefox desktop/safari

**Comment by jarednova** [comment]
@Levdbas thanks for the heads-up! are you for doing a PR to help us quickly resolve?

**Comment by Levdbas** [comment]
See #63 @jarednova

**Comment by gchtr** [comment]
@Levdbas Thanks for the hint and the pull request.

But I suspect that this issue is related to [Turbolinks](https://github.com/turbolinks/turbolinks), which we use to save the scroll position in the nav menu when navigating to other pages. I’ll have a look at it now.
