### ISSUE TITLE
References Section Broken

### ISSUE THREAD

**Issue by ahbyass** [timber/docs#8]
Seeing an issue where the references section will not load

https://timber.github.io/docs/reference/

Also on this section seeing the following error

https://timber.github.io/docs/reference/timber-post/#category

Warning: PHP Startup: Unable to load dynamic library ‘/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so’ - dlopen(/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so, 9): Symbol not found: _zend_signal_globals Referenced from: /usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so Expected in: flat namespace in /usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so in Unknown on line 0

**Comment by gchtr** [comment]
@AlexanderBMAS Thanks for pointing this out! There was an error in the last build of the docs 🙈. Should be fixed now.

**Comment by ahbyass** [comment]
No problem, thanks for the quick resolve.

**Comment by jarednova** [comment]
Thanks @AlexanderBMAS and @gchtr !
